name: Build and Push Radar V2 to Scaleway

on:
  push:
    branches:
      - v2-metier
  workflow_dispatch:

jobs:
  build-and-push-v2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build Docker image V2
        run: |
          docker build -t rg.fr-par.scw.cloud/namespace-loving-archimedes/radar-projets:v2 .

      - name: Push Docker image V2
        run: |
          docker push rg.fr-par.scw.cloud/namespace-loving-archimedes/radar-projets:v2
